FROM derekmerck/diana3:latest
LABEL maintainer="Derek Merck <derek.merck@ufl.edu>"

# This installs the package in developer mode, for easier local updates,
# editing of scripts, etc.
RUN git clone https://github.com/derekmerck/siren /opt/siren
#RUN pip install -e /opt/siren
